# Statistiques descriptives

On va travailler sur les données 'world-alcohol.csv' donc on commence par les importer.

In [17]:
import numpy as np
data = np.genfromtxt('world-alcohol.csv', delimiter=',', skip_header =1, dtype='U75')
print(data[:5,:])
data.shape

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']]


(3257, 5)

## Variable quantitative

In [16]:
#valeurs manquantes
filtre = data[:,4]==''
filtre.sum()

222

In [20]:
#on choisit de supprimer les lignes correspondantes
data2 = data[~filtre]
data2.shape

(3035, 5)

In [21]:
#conversion
consommation = data2[:,4].astype(float)

### Moyenne

In [23]:
np.mean(consommation)

1.2879604612850082

In [24]:
consommation.mean()

1.2879604612850082

In [33]:
np.average(consommation)

1.2879604612850082

In [30]:
#lister les méthodes d'un objet
dir(consommation)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

### Médiane

In [34]:
np.median(consommation)

0.31

### Maximum et minimum

In [35]:
print(max(consommation), ' et ', min(consommation))

13.5  et  0.0


### Mode

In [39]:
#import de la libraire stats
import scipy.stats as stat

In [46]:
filtre2 = consommation > 0.05
conso2 =  consommation[filtre2]
stat.mode(conso2)

ModeResult(mode=array([0.07]), count=array([37]))

In [40]:
stat.mode(consommation)

ModeResult(mode=array([0.]), count=array([713]))

### Écart-type (et variance)

In [41]:
np.std(consommation)

1.9637479274729108

In [44]:
np.var(consommation) - np.std(consommation)**2

0.0

### Quantiles

In [51]:
for i in range(1,11):
    decile = np.quantile(consommation,i/10)
    print(f'le {i}ème quantile est : {decile}')

le 1ème quantile est : 0.0
le 2ème quantile est : 0.0
le 3ème quantile est : 0.02
le 4ème quantile est : 0.10600000000000137
le 5ème quantile est : 0.31
le 6ème quantile est : 0.81
le 7ème quantile est : 1.5079999999999973
le 8ème quantile est : 2.32
le 9ème quantile est : 3.7619999999999982
le 10ème quantile est : 13.5


In [53]:
quartiles = np.quantile(consommation,[0.25,0.5,0.75])
quartiles

array([0.01, 0.31, 1.89])

In [56]:
percent =  np.percentile(consommation,[25,50,75])
percent

array([0.01, 0.31, 1.89])

In [58]:
stat.scoreatpercentile(consommation,[25,50,75])

array([0.01, 0.31, 1.89])

In [60]:
stat.scoreatpercentile(consommation,[i*10 for i in range(1,11)])

array([ 0.   ,  0.   ,  0.02 ,  0.106,  0.31 ,  0.81 ,  1.508,  2.32 ,
        3.762, 13.5  ])

In [61]:
stat.scoreatpercentile(consommation,[20,80])

array([0.  , 2.32])

## Variable qualitative

In [62]:
help(np.unique)

Help on function unique in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
    Find the unique elements of an array.
    
    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:
    
    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array
    
    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
        axis, if pro

In [69]:
#compter les occurences des modalités d'une colonne d'un tableau numpy
unique, counts = np.unique(data2[:,3], return_counts=True)
dico = {unique[i] : counts[i] for i in range(len(unique))}
array = np.asarray((unique, counts)).T
array

array([['Beer', '806'],
       ['Other', '617'],
       ['Spirits', '806'],
       ['Wine', '806']], dtype='<U75')